name: MatrixDeno

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        host:
          # Build on Ubuntu.
          - ubuntu-latest
        deno_version:
        # Latest Stable for Major
        - vx.x.x
        # 1.x Stable Major
        - v1.x
        # Canary
        - canary

    name: Deno v${{ matrix.deno_version }} with ${{ matrix.host }}
    steps:
      # Checkout Project, Setup, and Build.
      - name: Checkout Latest Files
        uses: actions/checkout@v2
        with:
          submodules: true
        run: |
          make setup
          make build-production
