name: Build and Validate

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]
defaults:
  run:
    shell: nu {0}

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Deno Validation Action
    steps:
      # Setup
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: hustcer/setup-nu@main
        with:
          version: '0.97.1'
      # Languages
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      # Handle
      - name: Build & Test
        run: nu devops.nu run-stage 10 20 30
