name: Snapshot Generator

on:
  push:
    branches: [main, staging, dev-**]
  pull_request:
    branches: [main, staging, dev-**]
  schedule:
    - cron: "0 0 1-31/4 * *"

jobs:
  analysis:
    runs-on: ubuntu-latest
    name: make _snapshot.json

    steps:
      - name: Checkout Latest Files
        uses: actions/checkout@v2
      - name: Initialize Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
      - name: ./scrips/update.js
        run: node ./scripts/update.js
      - name: commit snapshot
        uses: EndBug/add-and-commit@v6
        with:
          author_name: "Samuel Voeller"
          author_email: "samuel.voeller@mxsrv.amethyst.live"
          message: "chore: workflow-build make _snapshot.json"
          add: "_snapshot.json"
          push: "origin main -u --force"
          token: ${{ secrets.GITHUB_TOKEN }}
