name: Snapshot Generator

on:
  push:
    branches: [main, staging, dev-**]
  pull_request:
    branches: [main, staging, dev-**]
  schedule:
    - cron: "0 0 1-31/4 * *"

jobs:
  analysis:
    runs-on: ubuntu-latest
    name: make _snapshot.json

    steps:
      - name: Checkout Latest Files
        uses: actions/checkout@v2
      - name: Initialize Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
      - name: restore package-lock.json
        run: git restore 'package-lock.json'
      - name: make _snapshot.json
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "build(ci): make _snapshot.json"
          title: "[Automated] Update _snapshot.json from Discord"
          body: |
            - This is an automated build of the _snapshot.json file.

              Auto-generated by Github Actions on push, pull, and periodically.
          branch: dev-update_snapshot
